# Site settings
title: Machines and Intelligence 2013
email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Introduction module on machines and artificial intelligence with a focus on machine learning.
baseurl: "/mi2013/" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com/" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
